[package]
org = "nuvindu"
name = "rest_service"
version = "0.1.0"
distribution = "2201.13.5"
title = "rest-service"

[build-options]
sticky = true                                                                                                
observabilityIncluded = true 