[package]
org = "nuvindu"
name = "sf_trigger_email"
version = "0.1.0"
distribution = "2201.13.5"
title = "sf-trigger-email"

[build-options]
sticky = true

[[dependency]]
org="ballerinax"
name="salesforce.pubsub"
version="0.1.0"
repository="local"
